//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ServiceReferenceWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWeb.IServiceWeb")]
    public interface IServiceWeb {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeb/DoSomething", ReplyAction="http://tempuri.org/IServiceWeb/DoSomethingResponse")]
        void DoSomething();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeb/DoSomething", ReplyAction="http://tempuri.org/IServiceWeb/DoSomethingResponse")]
        System.Threading.Tasks.Task DoSomethingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeb/GetSomething", ReplyAction="http://tempuri.org/IServiceWeb/GetSomethingResponse")]
        string GetSomething();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeb/GetSomething", ReplyAction="http://tempuri.org/IServiceWeb/GetSomethingResponse")]
        System.Threading.Tasks.Task<string> GetSomethingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeb/PassSomethingToA", ReplyAction="http://tempuri.org/IServiceWeb/PassSomethingToAResponse")]
        string PassSomethingToA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeb/PassSomethingToA", ReplyAction="http://tempuri.org/IServiceWeb/PassSomethingToAResponse")]
        System.Threading.Tasks.Task<string> PassSomethingToAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeb/PassSomethingToB", ReplyAction="http://tempuri.org/IServiceWeb/PassSomethingToBResponse")]
        string PassSomethingToB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeb/PassSomethingToB", ReplyAction="http://tempuri.org/IServiceWeb/PassSomethingToBResponse")]
        System.Threading.Tasks.Task<string> PassSomethingToBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeb/PassSomethingToAToB", ReplyAction="http://tempuri.org/IServiceWeb/PassSomethingToAToBResponse")]
        string PassSomethingToAToB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeb/PassSomethingToAToB", ReplyAction="http://tempuri.org/IServiceWeb/PassSomethingToAToBResponse")]
        System.Threading.Tasks.Task<string> PassSomethingToAToBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeb/PassSomethingToBToA", ReplyAction="http://tempuri.org/IServiceWeb/PassSomethingToBToAResponse")]
        string PassSomethingToBToA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWeb/PassSomethingToBToA", ReplyAction="http://tempuri.org/IServiceWeb/PassSomethingToBToAResponse")]
        System.Threading.Tasks.Task<string> PassSomethingToBToAAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWebChannel : WebApp.ServiceReferenceWeb.IServiceWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWebClient : System.ServiceModel.ClientBase<WebApp.ServiceReferenceWeb.IServiceWeb>, WebApp.ServiceReferenceWeb.IServiceWeb {
        
        public ServiceWebClient() {
        }
        
        public ServiceWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoSomething() {
            base.Channel.DoSomething();
        }
        
        public System.Threading.Tasks.Task DoSomethingAsync() {
            return base.Channel.DoSomethingAsync();
        }
        
        public string GetSomething() {
            return base.Channel.GetSomething();
        }
        
        public System.Threading.Tasks.Task<string> GetSomethingAsync() {
            return base.Channel.GetSomethingAsync();
        }
        
        public string PassSomethingToA() {
            return base.Channel.PassSomethingToA();
        }
        
        public System.Threading.Tasks.Task<string> PassSomethingToAAsync() {
            return base.Channel.PassSomethingToAAsync();
        }
        
        public string PassSomethingToB() {
            return base.Channel.PassSomethingToB();
        }
        
        public System.Threading.Tasks.Task<string> PassSomethingToBAsync() {
            return base.Channel.PassSomethingToBAsync();
        }
        
        public string PassSomethingToAToB() {
            return base.Channel.PassSomethingToAToB();
        }
        
        public System.Threading.Tasks.Task<string> PassSomethingToAToBAsync() {
            return base.Channel.PassSomethingToAToBAsync();
        }
        
        public string PassSomethingToBToA() {
            return base.Channel.PassSomethingToBToA();
        }
        
        public System.Threading.Tasks.Task<string> PassSomethingToBToAAsync() {
            return base.Channel.PassSomethingToBToAAsync();
        }
    }
}
