//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ServiceReferenceB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceB.IServiceB")]
    public interface IServiceB {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceB/DoSomething", ReplyAction="http://tempuri.org/IServiceB/DoSomethingResponse")]
        void DoSomething();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceB/DoSomething", ReplyAction="http://tempuri.org/IServiceB/DoSomethingResponse")]
        System.Threading.Tasks.Task DoSomethingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceB/GetSomething", ReplyAction="http://tempuri.org/IServiceB/GetSomethingResponse")]
        string GetSomething();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceB/GetSomething", ReplyAction="http://tempuri.org/IServiceB/GetSomethingResponse")]
        System.Threading.Tasks.Task<string> GetSomethingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceB/PassSomethingToA", ReplyAction="http://tempuri.org/IServiceB/PassSomethingToAResponse")]
        string PassSomethingToA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceB/PassSomethingToA", ReplyAction="http://tempuri.org/IServiceB/PassSomethingToAResponse")]
        System.Threading.Tasks.Task<string> PassSomethingToAAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBChannel : WebApp.ServiceReferenceB.IServiceB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBClient : System.ServiceModel.ClientBase<WebApp.ServiceReferenceB.IServiceB>, WebApp.ServiceReferenceB.IServiceB {
        
        public ServiceBClient() {
        }
        
        public ServiceBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoSomething() {
            base.Channel.DoSomething();
        }
        
        public System.Threading.Tasks.Task DoSomethingAsync() {
            return base.Channel.DoSomethingAsync();
        }
        
        public string GetSomething() {
            return base.Channel.GetSomething();
        }
        
        public System.Threading.Tasks.Task<string> GetSomethingAsync() {
            return base.Channel.GetSomethingAsync();
        }
        
        public string PassSomethingToA() {
            return base.Channel.PassSomethingToA();
        }
        
        public System.Threading.Tasks.Task<string> PassSomethingToAAsync() {
            return base.Channel.PassSomethingToAAsync();
        }
    }
}
