//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ServiceReferenceA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceA.IServiceA")]
    public interface IServiceA {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceA/DoSomething", ReplyAction="http://tempuri.org/IServiceA/DoSomethingResponse")]
        void DoSomething();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceA/DoSomething", ReplyAction="http://tempuri.org/IServiceA/DoSomethingResponse")]
        System.Threading.Tasks.Task DoSomethingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceA/GetSomething", ReplyAction="http://tempuri.org/IServiceA/GetSomethingResponse")]
        string GetSomething();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceA/GetSomething", ReplyAction="http://tempuri.org/IServiceA/GetSomethingResponse")]
        System.Threading.Tasks.Task<string> GetSomethingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceA/PassSomethingToB", ReplyAction="http://tempuri.org/IServiceA/PassSomethingToBResponse")]
        string PassSomethingToB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceA/PassSomethingToB", ReplyAction="http://tempuri.org/IServiceA/PassSomethingToBResponse")]
        System.Threading.Tasks.Task<string> PassSomethingToBAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAChannel : WebApp.ServiceReferenceA.IServiceA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAClient : System.ServiceModel.ClientBase<WebApp.ServiceReferenceA.IServiceA>, WebApp.ServiceReferenceA.IServiceA {
        
        public ServiceAClient() {
        }
        
        public ServiceAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoSomething() {
            base.Channel.DoSomething();
        }
        
        public System.Threading.Tasks.Task DoSomethingAsync() {
            return base.Channel.DoSomethingAsync();
        }
        
        public string GetSomething() {
            return base.Channel.GetSomething();
        }
        
        public System.Threading.Tasks.Task<string> GetSomethingAsync() {
            return base.Channel.GetSomethingAsync();
        }
        
        public string PassSomethingToB() {
            return base.Channel.PassSomethingToB();
        }
        
        public System.Threading.Tasks.Task<string> PassSomethingToBAsync() {
            return base.Channel.PassSomethingToBAsync();
        }
    }
}
